### ISSUE TITLE
Session shutdown

### ISSUE THREAD

**Issue by kavinSpender** [llkat/rsockstun#1]
After some time of well working session shuts down with error:

[ERR] yamux: keepalive failed: i/o deadline reached
[ERR] yamux: Failed to read stream data:...
[WARN] yamux: failed to send go away: session shutdown
Got a client
Opening a stream
session shutdown

This was within 2 sec..

**Comment by llkat** [comment]
I think there was networks disconnect or some network errors.
[WARN] yamux - it is message from yamux multiplexer keepalive (one per 30 sec by default)
